export const UPDATE_PROJECTS = "UPDATE_PROJECTS";
export const REMOVE_PROJECT = "REMOVE_PROJECT";
export const SET_CURRENT_PROJECT = "SET_CURRENT_PROJECT";
export const ADD_PROJECT = "ADD_PROJECT";
export const LOADING = "LOADING";

export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const UPDATE_FAVORITES = "UPDATE_FAVORITES";
